// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ActiveHeader: typeof import('./components/ActiveHeader/index.vue')['default']
    PostCard: typeof import('./components/PostCard/index.vue')['default']
  }
}

export { }
